### ISSUE TITLE
Error fetching models: Unauthorized - Unauthorized

### ISSUE THREAD

**Issue by rafstahelin** [HartsyAI/SwarmUI-MagicPromptExtension#11]
entering OpenAi gpt api key and `https://api.openai.com/v1/chat/completions` but getting `Error fetching models: Unauthorized - Unauthorized`

![image](https://github.com/user-attachments/assets/70872c1c-a891-4e30-bdf9-2f2d7bc802a8)

tried with and without endpoint.

**Comment by kalebbroo** [comment]
Latest fix #12 stops the save settings button from deleting the API key. If you are still having issues please revert the config back to default, add your api key then try again. You should not need to enter a URL for Chat GPT its hardcoded already.
