### ISSUE TITLE
Prompt with magic prompt not being saved in meta-data.

### ISSUE THREAD

**Issue by Urabewe** [HartsyAI/SwarmUI-MagicPromptExtension#16]
When we use magic prompt, I would expect the prompt to be in the prompt input field and saved into the metadata. As is, the magic prompt is not being saved into meta data and only the original prompt is.

Also, when I generate, what is in the actual prompt field and what the image generating says is my prompt are two different things. Magic prompt is in the input field while the image still has old original prompt.

**Comment by Urabewe** [comment]
![image](https://github.com/user-attachments/assets/61275a14-f419-498b-b9dc-3e024874da21)

This is an image of what I'm talking about here.

**Comment by kalebbroo** [comment]
Can you update and check to see if this fixed the issue?

**Comment by Urabewe** [comment]
![image](https://github.com/user-attachments/assets/a83939ba-6f90-4d3a-a8c2-8f43a565e02c)

Perfect! Worked like a charm! I put "A photo of a cat" hit magic prompt, then hit generate. Which would have usually had the meta as "A photo of a cat" this time it was the magic prompt! 

Thanks!
