### ISSUE TITLE
[Feature Request] - More endpoint compatibility

### ISSUE THREAD

**Issue by aimerib** [HartsyAI/SwarmUI-MagicPromptExtension#3]
Oobabooga/text-generation-webui - OpenAI API through plugin (https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
ExLlamaV2 - OpenAI API (TabbyAPI)
GPT4ALL - OpenAI API
Llama.cpp - OpenAI API (https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md)
Llamafile - When llamafile is started, in addition to hosting a web UI chat server at http://127.0.0.1:8080/, an OpenAI API compatible chat completions endpoint is provided too.
vLLM - OpenAI API (https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
HuggingFace API - https://huggingface.co/docs/api-inference/index
KoboldAI/KoboldCPP - https://lite.koboldai.net/koboldcpp_api

Seems like most backends offer an OpenAI compatible endpoint, leaving only HuggingFace API and KoboldAI API left to implement once OpenAI endpoints are accepted. KoboldAI is hugely popular in LLM spaces, but mostly for chatting with character cards. If I had to guess on a reasonable implementation priority, it'd be:
* OpenAI API
* KoboldAI API
* HuggingFace API - Catch everything else, requires token flow for some models

**Comment by kalebbroo** [comment]
Some of this has been added. I do plan to add more so I am going to keep this issue open.

**Comment by MqtUA** [comment]
+1 for KoboldCPP

**Comment by MqtUA** [comment]
did work the day I coment here (just didnt see any models.
Also today I pulled latest commits, and extension tab diapered from ui

**Comment by MqtUA** [comment]
it also doesn't see Ollama models now

**Comment by kalebbroo** [comment]
> it also doesn't see Ollama models now

I am in Florida and was planning to do the "Release" of HartsyCore and announce it and all that. However I got hit by a hurricane. 

You changed it back to Ollama as the backend? Let me check if I broke something.

**Comment by MqtUA** [comment]
I have seen what's happening in Florida, and I hope you are okay there, please be cautious and stay safe.

**Comment by kalebbroo** [comment]
> First of all, I have seen what's happening in Florida, and I hope you are okay there, please be cautious and stay safe.
> 
> Second, I guess the issue with Ollama was because I messed with settings, specifically changed endpoint to the one for Kobold.
> 
> I restored config backup file and it worked.

I broke the save settings button. I just pushed an update to fix. It should now save settings properly. 

Just to confirm you said once you manually edited the settings the KobaldCCP worked?

**Comment by MqtUA** [comment]
> I broke the save settings button. I just pushed an update to fix. It should now save settings properly.
> 
> Just to confirm you said once you manually edited the settings the KobaldCCP worked?

Nope, that time Ollama worked after fixing cfg file.

I just tried switch KoboldCPP, but when I entered kobold endpoint http://localhost:5001 a tried to save, it showed error "An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set."

**Comment by 702enigma** [comment]
Did kobold end up working? Also has anyone gotten LM Studio to work I just get the invalid request url.

**Comment by kalebbroo** [comment]
> Did kobold end up working? Also has anyone gotten LM Studio to work I just get the invalid request url.

Does LM Studio use OpenAI API or do they use their own thing? I will have to actually download each of these to test because it does not seem like Kobald was working. Im sure its some small error I overlooked but It just means I will have to test each one...

**Comment by 702enigma** [comment]
> > Did kobold end up working? Also has anyone gotten LM Studio to work I just get the invalid request url.
> 
> Does LM Studio use OpenAI API or do they use their own thing? I will have to actually download each of these to test because it does not seem like Kobald was working. Im sure its some small error I overlooked but It just means I will have to test each one...

It's uses an openai like API. I'd rather use kobold so I hope at least that's added soon. Keep up the good work.

**Comment by kalebbroo** [comment]
Im not going to promise a timeframe. but, yes. Soon.

**Comment by kalebbroo** [comment]
Update and test on any openaiapi backend you guys have. Let me know if you get any errors or if you want anything to work a little differently. Not announcing this yet until I have more playtests done but it should be working.

**Comment by MqtUA** [comment]
It now works well with KoboldCPP. Thank you!

**Comment by kalebbroo** [comment]
great to hear. Im going to close this issue until I decide to add more support for things.
